feat: add shellcheck make target
korrel8r/korrel8r pull request #109
Opened 2024-04-10 17:06 UTC by vprashar2929

This PR adds `shellcheck` target which installs shellcheck tool locally. `make lint` will also run shellcheck

2024-04-12 13:43 UTC, alanconway requested changes
Minor suggestion, otherwise great.

2024-04-12 13:43 UTC, alanconway commented on Makefile
> +lint: $(VERSION_TXT) $(GOLANGCI_LINT) $(SHFMT) shellcheck ## Run the linter to find and fix code style problems.
Use Make dependenciees to download shellcheck:
```suggestion
SHELLCHECK=$(LOCALBIN)/shellcheck
lint: $(VERSION_TXT) $(GOLANGCI_LINT) $(SHFMT) $(SHELLCHECK) ## Run the linter to find and fix code style problems.
```

$(SHELLCHECK):
        hack/download_shellcheck.sh $(LOCALBIN)/shellcheck

2024-04-12 13:43 UTC, alanconway commented on Makefile
> +.PHONY: shellcheck
Move to shell script hack/download_shellcheck.sh, no need to check for existence this make rule will only be invoked if shellcheck is missing

2024-05-02 11:13 UTC, vprashar2929 commented
cc: @alanconway if it looks good can we merge this?

2024-05-08 20:52 UTC, merged