feat: add shellcheck and shfmt
korrel8r/korrel8r pull request #94
Opened 2024-03-15 09:23 UTC by vprashar2929

This PR addresses #88 and #87:
* Adds `shfmt` and `shellcheck` to format and lint shell scripts.
* Modify the existing GH workflow to run `fmt` and `shellcheck` jobs.
* Update the existing scripts accordingly.
* Removes `wait-for-csv.sh` as it is not used anymore.

2024-03-18 14:30 UTC, alanconway requested changes
Looks good, a couple of suggestions and I'll merge it.

2024-03-18 14:30 UTC, alanconway commented on Makefile
> +.PHONY: fmt
go fmt is not necessary. `golangci-lint run --fix` includes the actions of `go fmt` and is faster than running separately.

2024-03-18 14:30 UTC, alanconway commented on Makefile
> +	$(SHFMT) -l -w ./**/*.sh
Suggest running $(SHFMT) as  part of the lint: target. That will simplify the git actions and lets devs ensure they are "lint and format clean" with one command.

2024-03-18 14:30 UTC, alanconway commented on hack/copyright.sh
> +FILES=$(find . -name '*.go' -print0 | xargs grep -L "$LINE")
```suggestion
FILES=$(find . -name '*.go' -print0 | xargs -0 grep -L "$LINE")
```

2024-03-21 14:38 UTC, alanconway commented
@vprashar2929 There are some very minor clashes with latest main (my changes, sorry!), can you please:
- Squash the PR to a single commit
- Rebase on latest main
This project aims at keeping  a linear history, so rebase is preferred over merge.

2024-03-21 17:19 UTC, vprashar2929 commented
No problem Alan 😊.  All green now

2024-04-01 10:08 UTC, vprashar2929 commented
@alanconway Can you help merge this PR? I think auto-merge is struck on the build check

2024-04-09 00:19 UTC, closed without merging

2024-04-09 00:21 UTC, alanconway commented
Manually pushed as commit 0a4bf66.
Restored build.xml to original - single "build" job with multiple steps. 
shfmt is run via "make lint" so no need for a separate job.